IT_project_2021/Controllers/HomeController.cs
using IT_project_2021.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IT_project_2021.Controllers
{
    [RequireHttps]
    public class HomeController : Controller
    {
        [AllowAnonymous]
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                ApplicationUser user = System.Web.HttpContext
                    .Current
                    .GetOwinContext()
                    .GetUserManager<ApplicationUserManager>()
                    .FindByEmail(User.Identity.Name);

                //ViewBag.FullName = String.Format("{0} {1}",
                //    user.FirstName,
                //    user.LastName
                //);
            }

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

IT_project_2021/Controllers/WorkoutController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IT_project_2021.Models;
using IT_project_2021.Models.repo;

namespace IT_project_2021.Controllers
{
    public class WorkoutController : Controller
    {
        private UserContext db = new UserContext();
        public DateTime ExerciseDate { get; set; }

        // GET: Workout
        public ActionResult Index()
        {
            return View(db.Exercises.ToList());
        }

        // GET: Workout/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExercisesModel exercisesModel = db.Exercises.Find(id);
            if (exercisesModel == null)
            {
                return HttpNotFound();
            }
            return View(exercisesModel);
        }

        // GET: Workout/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Workout/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ExerciseDate,ExerciseName,kgLifted,Reps,Sets,ChooseExercises")] ExercisesModel exercisesModel)
        {
            if (ModelState.IsValid)
            {
                var newDate = new TimeSpan(DateTime.UtcNow.Ticks-ExerciseDate.Ticks);
                
                exercisesModel.ExerciseDate = DateTime.Now;
                db.Exercises.Add(exercisesModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(exercisesModel);
        }


        // GET: Workout/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExercisesModel exercisesModel = db.Exercises.Find(id);
            if (exercisesModel == null)
            {
                return HttpNotFound();
            }
            return View(exercisesModel);
        }

        // POST: Workout/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ExerciseDate,ExerciseName,kgLifted,Reps,Sets")] ExercisesModel exercisesModel)
        {
            if (ModelState.IsValid)
            {
                exercisesModel.ExerciseDate=ExerciseDate;
                db.Entry(exercisesModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(exercisesModel);
        }

        // GET: Workout/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExercisesModel exercisesModel = db.Exercises.Find(id);
            if (exercisesModel == null)
            {
                return HttpNotFound();
            }
            return View(exercisesModel);
        }

        // POST: Workout/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ExercisesModel exercisesModel = db.Exercises.Find(id);
            db.Exercises.Remove(exercisesModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IT_project_2021/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

IT_project_2021/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

IT_project_2021/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@Html.Partial("_FirstPart")

@Html.Partial("_MiddlePart")

@if (User.IsInRole("Administrator"))
{
    @Html.Partial("_AdminPrivilegii")}
}



<style>
    li {
        padding-bottom: 5px;
    }

    .kopce {
        width: 100%;
        display: block;
    }

    .col-md-4 {
        margin-top: 22px;
    }

    .funct {
        margin-top: 22px;
        margin-left: 1%;
        margin-right: 1%;
    }

    .image {
        width: 100%;
        height: 100%;
    }

    body {
        background-image: url('../../Photos/gym.jpg');
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
    }

   
</style>

IT_project_2021/Views/Home/_AdminPrivilegii.cshtml
<div class="panel panel-default panel-body">
    <div class="panel panel-default funct">
        <div class="panel-heading" style="background-color: paleturquoise">
            <h2>Admin Privilages</h2>
        </div>
        <div class="panel-body">
            <ul style="list-style-type: none; padding-left: 0; margin-top: 15px">
                <li>
                    @Html.ActionLink("Change User Privilages", "AddUserToRole", "Account", null, new { @class = "btn btn-info kopce", style = "color: red; text-decoration:none;" })
                </li>
                <li>
                    @Html.ActionLink("What else???", "Index", "Workout", null, new { @class = "btn btn-info kopce", style = "color: white; text-decoration:none;" })
                </li>
            </ul>
        </div>
    </div>
</div>

IT_project_2021/Views/Home/_FirstPart.cshtml
<div class="jumbotron">
    <h1>Fitnes Niko</h1>
    <h2>Best Gym In Town</h2>

    @if (User.Identity.IsAuthenticated)
    {
        <p class="lead">Welcome: </p>
        @Html.ActionLink("Sucessfull Lifts", "Index", "Workout", null, htmlAttributes: new { @class = "btn btn-info btn-lg inf" })
    }

    


</div>

<style>
    
    .marg {
        margin-right: 5px;
    }

    h1,h2{
        text-align:center;
    }

    .inf {
        margin-left: -5px;
    }
</style>

IT_project_2021/Views/Home/_MiddlePart.cshtml
<div class="row">
    <div class="panel panel-default panel-body" id="divking">

        <div id="temp" class="col-md-4">
            <div class="panel panel-default" id="toYellow">
                <div class="panel-heading">
                    <h2>New Here? Get Started!</h2>
                </div>
                <div class="panel-body">
                    @Html.ActionLink("Add Workout Routine", "Create", "Workout", null, new { @class = "btn btn-info kopce", style = "color: white; text-decoration:none;" })
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-default" id="toYellow">
                <div class="panel-heading">
                    <h2>Write down your progress!</h2>
                </div>
                <div class="panel-body">
                    @Html.ActionLink("Add Lift", "Create", "Workout", null, new { @class = "btn btn-info kopce", style = "color: white; text-decoration:none;" })
                </div>
            </div>
        </div>
        
    </div>
</div>


<style>
    #temp{
        margin-left:180px
    }


</style>